### PR TITLE
Added To Do List Tool

### PR DESCRIPTION
**Pull request by akshitaPrajapati**

### CODE REVIEW

**Comment by kod-it** [comment]
fetch the latest commits and link your tool with the home page...
i.e., edit the navbar for your tool & add a card on the index page that redirects to your app from the index...

**Comment by kod-it** [comment]
Though ur To Do List Tool was really impressive.. please do the above mentioned changes and send the PR again @akshitaPrajapati

**Comment by akshitaPrajapati** [comment]
Done!

**Comment by kod-it** [comment]
checkout for conflicts please... @akshitaPrajapati

**Pull request closed without merging**
