### PR TITLE
Added Unit Converter tool

### PR DESCRIPTION
**Pull request by aswinikalyan30**
Resolves issue #22 
Units conversion for Area, length, mass, power, temperature, speed are provided

### CODE REVIEW

**Comment by aswinikalyan30** [comment]
Hey, I've added a few more changes to the index.html, providing a proper description for other tools, and added a card for my tool too!

**Comment by neha030** [comment]
@aswinikalyan30 Your PR is showing conflict . Please resolve the conflict .

**Comment by aswinikalyan30** [comment]
> @aswinikalyan30 Your PR is showing conflict . Please resolve the conflict .

Hey, the conflict is arising because everyone's updating the index. I'm not sure if I should edit it or not

**Comment by neha030** [comment]
> > @aswinikalyan30 Your PR is showing conflict . Please resolve the conflict .
> 
> Hey, the conflict is arising because everyone's updating the index. I'm not sure if I should edit it or not

You need to resolve the conflict to get it merged

**Comment by aswinikalyan30** [comment]
I've resolved the conflict! Please merge before anyone else faces this.

**Comment by neha030** [comment]
Good work @aswinikalyan30 . Keep Contributing .

**Pull request merged**
